# PSUtil Command Reference

 - [Add-PSUString](PSUtil/Add-PSUString.html)
 - [Convert-PSUObject](PSUtil/Convert-PSUObject.html)
 - [Expand-PSUObject](PSUtil/Expand-PSUObject.html)
 - [Format-PSUString](PSUtil/Format-PSUString.html)
 - [Invoke-PSUDesktop](PSUtil/Invoke-PSUDesktop.html)
 - [Invoke-PSUExplorer](PSUtil/Invoke-PSUExplorer.html)
 - [Invoke-PSUTemp](PSUtil/Invoke-PSUTemp.html)
 - [Join-PSUString](PSUtil/Join-PSUString.html)
 - [Register-PSUObjectConversion](PSUtil/Register-PSUObjectConversion.html)
 - [Remove-PSUString](PSUtil/Remove-PSUString.html)
 - [Select-PSUObjectSample](PSUtil/Select-PSUObjectSample.html)
 - [Set-PSUObjectType](PSUtil/Set-PSUObjectType.html)
 - [Set-PSUShell](PSUtil/Set-PSUShell.html)
 - [Set-PSUString](PSUtil/Set-PSUString.html)
 - [Split-PSUString](PSUtil/Split-PSUString.html)
